language: es

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: "DIETClassifier"
  epochs: 100
  intent_tokenization_flag: true
  intent_split_symbol: "+"
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 3
- name: ftfeat.FastTextFeaturizer
  cache_dir: ""
  file: "cc.es.100.bin"
- name: printer.Printer
  alias: after fasttext
- name: printer.Printer
  alias: after outlier
- name: DIETClassifier
  epochs: 100
- name: EntitySynonymMapper

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
